name: love_calcu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  hive:
  liquid_swipe: ^3.0.0
  smooth_page_indicator:
  flutter_screenutil:
  flashy_tab_bar2: 
  dio:
  awesome_snackbar_content: ^0.0.8
  animated_background: ^2.0.0
  shared_preferences:
  google_fonts: 
  path_provider:
  countup: ^0.1.4
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  line_awesome_flutter: ^2.0.0
  sqflite:
  intl:
  flutter_native_splash:
  sqlite_viewer: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/